services:
- postgresql
before_script:
- psql -c 'create database sheaf_test;' -U postgres
- RAILS_ENV=test bundle exec rake db:migrate
- bundle exec rake db:seed
script:
- bundle exec rake rspec
language: ruby
rvm:
- 2.3.1
